### ISSUE TITLE
Better codec configuration

### ISSUE THREAD

**Issue by Sean-Der** [pion/webrtc-v3-design#8]
A user shouldn't have to take SSRC/PayloadType into consideration

A user should be able to configure fmtp lines. We need to be careful that exposing this we don't force users to juggle values.

**Comment by jeremija** [comment]
Is this about fixing the issue with `webrtc.MediaEngine` and cross-browser compatibility? For example, Chrome uses `PayloadType=96` for VP8, whereas Firefox does not, and therefore the video does not play when RTP packets are transferred through Pion.

**Comment by Sean-Der** [comment]
Yes exactly @jeremija !

Instead you will just deal with codecs (VP8....) on the public API so you don’t ever even need to think about 96 (Or a different value) again!

**Comment by jeremija** [comment]
Nice - let me know if I can help with this in any way. Don't have as much free time as I used to, but I love contributing to Pion 🙂 

I think we'd have to keep a reverse lookup table for each supported codec in each peer connection. For example, if during negotiation it turns out that one peer supports `VP8/90000` with payload type `96`, and the other one `VP8/90000` with payload type `111`, we'd need to be able to figure out that these are the same codecs. Pion should then worry about transforming the `PayloadType`s automatically when writing RTP packets between peer connections.

However, it seems we'd also need to include the `fmtp` and the number of channels in this lookup table.

WDYT?

**Comment by Sean-Der** [comment]
@jeremija I would love your help :)  If we can get the API all 'compiling' in this repo (but not actually doing anything) we can start doing the actual code.

So the lookup table will be [RtpCodecCapability ](https://draft.ortc.org/#dom-rtcrtpcodeccapability) that the public API requires you to configure. You will have a list of them, and then internally we set all the PayloadTypes. During signaling internally all the payload types will be set.

Then when you write you just pass around a `RtpCodecCapability` (set it per Track and be done forever) and all the SSRC/PayloadType setting is done! Instead of managing SSRC/PayloadTypes the user now needs to think in terms of `RtpCodecCapability`

**Comment by jeremija** [comment]
@Sean-Der I added a small change that tries to address this. LMK what you think!

**Comment by Sean-Der** [comment]
I feel good about this! We have parameters now, and users configure it via public API. Users could easily send AV1/H265/$x if they wanted also, we give the flexibility to send w/e they want.
